### ISSUE TITLE
Fast Refresh with Reason-React

### ISSUE THREAD

**Issue by jfrolich** [reasonml/reason-react#549] opened 2020-04-29 03:17 UTC
Fast Refresh is triggering a full refresh when a file exports anything other than components. With `reason-react` when you have multiple components in a file you need to create submodules, which will be exported as objects with a `make` function that is the actual component. This however triggers a full refresh. Any ideas on how we can make fast refresh work in this situation (perhaps a PR to the fast-refresh implementation of react?).

**Comment by cknitt** [comment] 2020-04-29 05:28
I found that this seems to be the case only for "root" components like the app root itself and e.g. React Navigation screens.

My workaround, if the submodules are only for internal use by the main component in the file, is to provide a .rei file that only exports the `make` function of the file's main component like so:

```reason
// For Fast Refresh to actually work,
// the root component may only have a single export.

[@react.component]
let make: unit => React.element;
```

Of course it would be nice if this was fixed in the fast refresh implementation itself.

**Comment by jfrolich** [comment] 2020-04-29 05:52
> I found that this seems to be the case only for "root" components like the app root itself and e.g. React Navigation screens.
> 
> My workaround, if the submodules are only for internal use by the main component in the file, is to provide a .rei file that only exports the `make` function of the file's main component like so:
> 
> ```reason
> // For Fast Refresh to actually work,
> // the root component may only have a single export.
> 
> [@react.component]
> let make: unit => React.element;
> ```
> 
> Of course it would be nice if this was fixed in the fast refresh implementation itself.

Yeah I know about the workarounds. I also create `rei` files for this now. With `react-native-navigation` this occurs for each component and not only for the top components, and if you have a modal open it even completely crashes :), so not able to fast refresh is not a great DX.

**Comment by rickyvetter** [comment] 2020-04-29 14:27
I'm not sure I have enough context on what is preventing this. See https://reactnative.dev/docs/fast-refresh

> If you edit a module that only exports React component(s)

It sounds like it should support components exported as `make` or any other key as long as that is all that's exported. Can you confirm that it doesn't work on components that only have `make` as a React component exported? If so, it sounds like a bug on their side that we should champion a resolution for.

If the issue is other exports then `.rei` seems like one solution. I know BuckleScript is also looking at inline private annotations as well.

Closing this for now - if it's an issue with clean {make} exports please re-open and we'll keep as tracking for the external issue to make sure we can get involved. If it's an issue with additional exports in Reason being more common then I think BuckleScript is a more suitable place to chat about it.

**Closed by rickyvetter** 2020-04-29 14:27 UTC

**Comment by jfrolich** [comment] 2020-04-30 01:25
> It sounds like it should support components exported as make or any other key as long as that is all that's exported. Can you confirm that it doesn't work on components that only have make as a React component exported? If so, it sounds like a bug on their side that we should champion a resolution for.

Yes that would be a solution, would be good to propose this. It's not necessarily a bug, but this will make sure it works with the `reason-react` components.
