### ISSUE TITLE
[@react.component] breaks when used with a function that has a explicit polymorphic locally abstract type

### ISSUE THREAD

**Issue by gugahoa** [reasonml/reason-react#452] opened 2019-06-28 00:28 UTC
Minimal example:
https://reasonml.github.io/try.html?rrjsx=true&reason=NoAQRgzgdAxg9gOwGYEsDmACA3gKwgDwC4MBmAXwF0BuAKBoFs4ATAVwBsBTDAcQCcOOAFxQJMAXmw0MGUPwCGMQbDj0ADog4JBFKRk6CM9OQGsuEgBSCAnqq5yANBgB+SOHGJxVwxObkBKMQB+PwwxAD5JaWkAHjAWQUFECKwAJQ4FJQhBXhE0cwAiAAkONjY4AEJy-L8yDGiAejiEpN0yWja6NIyAEQB5AFk0qH4EJg5eABU4AFFOek1BAHUUQQALAEkmc2i+AWFRDHqwx3zVfgA3FA4Ad2qqIA

Error message:
Fatal error: exception Invalid_argument("react.component calls can only be on function definitions or component wrappers (forwardRef, memo).")

**Comment by mlms13** [comment] 2019-09-18 22:08
#466 is a duplicate of this issue.

**Comment by peterpme** [comment] 2020-04-22 22:18
Hey @gugahoa 

In an effort to clean up the repo (and given how old this issue is) I'm going to close this out for now. 

Sorry about the delay. Please re-open if its still relevant.

Thanks!

**Closed by peterpme** 2020-04-22 22:18 UTC
